version: '3.8'

services:
  physicssim-console:
    build:
      context: .
      dockerfile: PhysicsSim.Console/Dockerfile
    image: physicssim-console
    container_name: physicssim-console
    restart: unless-stopped

  physicssim-web:
    build:
      context: .
      dockerfile: PhysicsSim.Web/Dockerfile
    image: physicssim-web
    container_name: physicssim-web
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
