name: Build and Push Console and Web Docker Images

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag name sanitization
        id: tag
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME//\//-}"
          echo "TAG_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "TAG_NAME=${BRANCH_NAME}"

      - name: Build and Push Console Image
        uses: docker/build-push-action@v4
        with:
          context: ./PhysicsSim.Console
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/physics-sim-console:${{ env.TAG_NAME }}
            ${{ github.ref_name == 'main' && format('{0}/physics-sim-console:latest', secrets.DOCKER_USERNAME) || '' }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/physics-sim-console:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/physics-sim-console:cache,mode=max

      - name: Build and Push Web Image
        uses: docker/build-push-action@v4
        with:
          context: ./PhysicsSim.Web
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/physics-sim-web:${{ env.TAG_NAME }}
            ${{ github.ref_name == 'main' && format('{0}/physics-sim-web:latest', secrets.DOCKER_USERNAME) || '' }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/physics-sim-web:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/physics-sim-web:cache,mode=max

        # - name: Build and push Docker image
        # uses: docker/build-push-action@v4
        # with:
        #   context: .
        #   push: true
        #   tags: | 
        #     ${{ secrets.DOCKER_USERNAME }}/physics-sim:${{ env.TAG_NAME }}
        #     ${{ github.ref_name == 'main' && format('{0}/physics-sim:latest', secrets.DOCKER_USERNAME) || '' }}
        #   cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/physics-sim:cache
        #   cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/physics-sim:cache,mode=max