name: Build Docker Image

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate valid Docker tag
        id: tag
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME//\//-}"
          echo "TAG_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "TAG_NAME=${BRANCH_NAME}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: | 
            ${{ secrets.DOCKER_USERNAME }}/physics-sim:${{ env.TAG_NAME }}
            ${{ github.ref_name == 'main' && format('{0}/physics-sim:latest', secrets.DOCKER_USERNAME) || '' }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/physics-sim:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/physics-sim:cache,mode=max